---
id: mirlyn
metadata:
  name: Catalog
  short_descr: The Library Catalog.
source: mirlyn

new_parser: true
search_field_default: all_fields
search_attr_defaults:
  mm: $default_mm
  mm.autoRelax: $mm.autoRelax
  tie: $tie

search_fields:
  title:
    qf: title_common_exact^1000 title_common^120 title_equiv^60 title_rest^30 series^10 series2^5
    pf: serialTitle_common_exact^600 title_common_exact^500 title_l^150 title_common^100 title_a_exact^50 title_top^30 title_rest^20 series^3 series2^2
  author:
    qf: mainauthor^20 author^10 author2^5 author_top^2 author_rest^1
    pf: mainauthor^100 author^50 author2^20 author_top^5 author_rest^2
  all_fields:
    qf: >-
      allfieldsProper^2
      allfields^1
      title_common^50
      title_equiv^10
      mainauthor^80
      author^50
      isbn
      issn
      oclc
      lccn
      barcode
      htid
      callnosearch

    pf: >-
      title_equiv^40
      title_top^20
      title_rest^10

      author^80
      author_top^30
      author_rest^20


    pf2: >-
      title_author^500
      title_equiv^80
      title_l^50

    ps2: 2
    boost: >-
      product(
        if(termfreq('format', 'Journal'), 1.4, 1),
        max(
          map(
          query({!field f=title_common_exact v=$q}, 1), 0, 1, 1, 180
        ),
        map(
          query({!field f=title_equiv_exact v=$q}, 1), 0, 1, 1, 50
        ),
        map(
          query({!field f=title_a_exact v=$q}, 1), 0, 1, 1, 10
        )),
        map(
            query({!dismax f=title_author v=$q mm="100%"}, 1), 0, 1, 1, 50
          ),
      )

  series:
    pf: series^500 series2^50
    qf: series^200 series2^50

  serial_title:
    pf: serialTitle_common_exact^600 serialTitle_common_l^300 serialTitle_common^100 serialTitle_a_exact^40  serialTitle_equiv^20
    qf: serialTitle_common^30 serialTitle_equiv^15 serialTitle_rest^10

  journal_title:
    pf: serialTitle_common_exact^600 serialTitle_common_l^300 serialTitle_common^100 serialTitle_a_exact^40  serialTitle_equiv^20
    qf: serialTitle_common^30 serialTitle_equiv^15 serialTitle_rest^10

#  journal_title:
#    pf: serialTitle_ab^25000 serialTitle_a^15000 serialTitleProper^1200
#    qf: serialTitleProper^120  serialTitle^30 serialTitle_rest^10

  subject:
    pf: topicProper^5 topic^1 fullgeographic^1 fullgenre^1 era^1
    qf: topicProper^5 topic^1 fullgeographic^1 fullgenre^1 era^1

  subject2:
    pf: topicProper^5 topic^1
    qf: topicProper^5 topic^1

  academic_discipline:
    pf: hlb3^10
    qf: hlb3^1

  realauth:
    pf: authorStr^10
    qf: authorStr^1

  isn:
    pf: issn^10 isbn^10 lccn^5 oclc^5 sdrnum^2 isn_related^2 rptnum ctrlnum ht_id  id id_int barcode
    qf: issn^10 isbn^10 lccn^5 oclc^5 sdrnum^2 isn_related^2 rptnum ctrlnum ht_id  id id_int barcode

  publisher:
    pf: publisher^10
    qf: publisher

  publication_date:
    pf: publishDate
    qf: publishDate

  title_starts_with:
    pf: serialTitle_common_l^10 title_l^5
    qf: title_l

  call_number_starts_with:
    pf: callnosearch sudoc
    qf: callnosearch sudoc



# Note that solr_params will _not_ work if they reference '$q' or whatnot, since
# these are common to the whole search and those are specific to one edismax
# clause. (Noted because I tried to reference the allfields boost, which didn't work).

solr_params:
  default_mm: "2<-1 5<67%"
  mm.autoRelax: true
  tie: 0.1

qt: standard
has_holdings: true
has_get_this: true
href:
  field: path_alias
  prefix: http://mirlyn.lib.umich.edu/Record/

default_sort: relevance
sorts:
  relevance: relevance
  date_asc: date_asc
  date_desc: date_desc
  author_asc: author_asc
  author_desc: author_desc
  cat_date: date_added
  mirlyn_title_asc: mirlyn_title_asc
  mirlyn_title_desc: mirlyn_title_desc
fields:
  - id
  - allfields
  - mirlyn_format
  - position
  - marc_title
  - marc_ris_title
  - main_author
  - preferred_title
  - related_title
  - other_titles
  - new_title
  - new_title_issn
  - previous_title
  - previous_title_issn
  - author
  - contributors
  - published_brief
  - created
  - distributed
  - manufactured
  - edition
  - series
  - series_statement
  - biography_history
  - mirlyn_summary
  - in_collection
  - marc_access
  - terms_of_use
  - language
  - language_note
  - performers
  - date_place_of_event
  - related_items
  - numbering
  - current_publication_frequency
  - former_publication_frequency
  - numbering_notes
  - source_of_description_note
  - copy_specific_note
  - references
  - copyright_status_information
  - note
  - arrangement
  - copyright
  - physical_description
  - reproduction_note
  - original_version_note
  - playing_time
  - media_format
  - audience
  - awards
  - production_credits
  - bibliography
  - isbn
  - marc_issn
  - oclc
  - gov_doc_no
  - publisher_number
  - report_number
  - chronology
  - place
  - printer
  - association
  - marc_bookplate
  - lcsh_subjects
  - other_subjects
  - academic_discipline
  - contents_listing
  - bookplate
# Below this ??
  - mirlyn_published_year
  - links
  - callnumber
  - institution
  - place_of_publication
  - extended_summary
  - marc_published
  - full_previous_title
  - full_new_title
  - indexes
  - institution
  - journal_title
  - year_of_publication
  - marc_record
  - display_date
#  - catalog_resource_access
  - marc_300_a
  - marc_264_b
  - marc_856_u
# Search specific fields
  - title_starts_with
  - call_number_starts_with
  - subject
  - isn
# Header Components
  - select_box
  - favorites_icon
  - favorites_tags
# Citation specfic fields, not for display
  - ris_main_author
  - ris_contributors
  - csl_main_author
  - csl_contributor
  - csl_editor
  - csl_publisher
  - csl_publisher_place
  - mirlyn_csl_type
  - marc_csl_title
  - z3988_rft_val_fmt
  - z3988_rft_genre
  - z3988_sid
  - catalog_rfr_id

facets:
  - available_online
  - search_only
  - mirlyn_format
  - subject
  - date_of_publication
  - language
  - availability
  - location
  - academic_discipline
  - author
  - place_of_publication_filter
  - region
  - institution
  - collection
  - building

hierarchy:
  load_inst: <%= ENV['SPECTRUM_INST_LOCATION_FILES_DIR'] || "/www/vufind/web/mirlyn/web/conf" %>/instLocs.yaml
  load_coll: <%= ENV['SPECTRUM_INST_LOCATION_FILES_DIR'] || "/www/vufind/web/mirlyn/web/conf" %>/locColl.yaml
  field: Library
  uid: institution
  aliases:
    top:
      all: All libraries
      aa: U-M Ann Arbor Libraries
      flint: Flint Thompson Library
      umtri: Transportation Research Institute Library (UMTRI)
      bentley: Bentley Historical Library
      clements: William L. Clements Library
    tr:
      institution:
        "All Libraries": "*"
        "All libraries": "*"
        "U-M Ann Arbor Libraries": "UM Ann Arbor Libraries"
      location:
        "All Locations": "*"
        "All locations": "*"
      collection:
        "All Collections": "*"
        "All collections": "*"
  children:
    field: Location
    uid: location
    children:
      field: Collection
      uid: collection
