---
clements:
  sublibs:
    CLEM: William L. Clements
bentley:
  sublibs:
    BENT: Bentley Historical
#umtri:
#  sublibs:
#    UMTRI: Transportation Research Institute Library
flint:
  sublibs:
    FLINT: Flint Thompson Library
aa:
  sublibs:
    ALL: All locations
    AAEL: Art Architecture & Engineering
    FVL: Askwith Media Library
    BSTA: Biological Station
    BUHR: Buhr Shelving Facility
    CSCAR: CSCAR - Rackham Building
    FINE: Fine Arts
    HATCH: Hatcher Graduate
    HSRS: Health Sciences Remote Shelving
    MUSM: Research Museums Center
    MUSIC: Music
    SHAP: Shapiro
    SPEC: Special Collections
    TAUB: Taubman Health Sciences
all:
  sublibs:
    ALL: All locations
    AAEL: Art Architecture & Engineering
    FVL: Askwith Media Library
    BENT: Bentley Historical
    BSTA: Biological Station
    BUHR: Buhr Shelving Facility
    CSCAR: CSCAR - Rackham Building
    FINE: Fine Arts
    FLINT: Flint Thompson Library
    HATCH: Hatcher Graduate
    HSRS: Health Sciences Remote Shelving
    MUSM: Research Museums Center
    MUSIC: Music
    SHAP: Shapiro
    SPEC: Special Collections
    TAUB: Taubman Health Sciences
    CLEM: William L. Clements
